const payload = {
    data: {
        hotel: "Royal Raj Hotel",
        hotelAddress: "Rajshahi",
        month: "July 2025",
        downloadType: "Booking.com",
        invoiceNo: "25012009",
        invoiceDate: "01 September 2025",
        invoices: [
            {
                id: 13,
                inv_no: "202508134830",
                inv_date: "2025-08-13",
                total_amount: "244.00",
                total_advance: null,
                currency_id: null,
                hotelName: "Royal Raj Hotel",
                hotel_id: 2,
                hotelAddress: "Rajshahi",
                commissionType: "percent",
                hotelCollectsCommission: "20",
                expediaCollectsCommission: "15",
                reservation_id: 4,
                guest_name: "Royal Raj 1",
                reservation_no: "465451616",
                status_id: 1,
                check_in: "2025-07-13",
                check_out: "2025-07-15",
                rate_id: 1,
                source_id: 1,
                payment_method_id: 1,
                hotel: {
                    id: 2,
                    hotelName: "Royal Raj Hotel",
                    hotelAddress: "Rajshahi",
                },
                reservation: {
                    id: 4,
                    status_id: 1,
                    reservation_no: "465451616",
                    check_in: "2025-07-13",
                    check_out: "2025-07-15",
                    guest_name: "Royal Raj 1",
                    rate_id: 1,
                    source_id: 1,
                    payment_method_id: 1,
                },
                hotel_invoice_rooms: [
                    {
                        id: 10,
                        room_name: "Single Room",
                        total_room: 2,
                        total_price: "2.00",
                        currency_id: 1,
                        exchange_rate: "122.00",
                        commission_type: "percent",
                        commission_value: "20.00",
                        hotel_given_price: null,
                    },
                ],
            },
            {
                id: 19,
                inv_no: "202508307611",
                inv_date: "2025-08-30",
                total_amount: "36844.00",
                total_advance: null,
                currency_id: null,
                hotelName: "Royal Raj Hotel",
                hotel_id: 2,
                hotelAddress: "Rajshahi",
                commissionType: "percent",
                hotelCollectsCommission: "20",
                expediaCollectsCommission: "15",
                reservation_id: 4,
                guest_name: "Royal Raj 1",
                reservation_no: "465451616",
                status_id: 1,
                check_in: "2025-07-13",
                check_out: "2025-07-15",
                rate_id: 1,
                source_id: 1,
                payment_method_id: 1,
                hotel: {
                    id: 2,
                    hotelName: "Royal Raj Hotel",
                    hotelAddress: "Rajshahi",
                },
                reservation: {
                    id: 4,
                    status_id: 1,
                    reservation_no: "465451616",
                    check_in: "2025-07-13",
                    check_out: "2025-07-15",
                    guest_name: "Royal Raj 1",
                    rate_id: 1,
                    source_id: 1,
                    payment_method_id: 1,
                },
                hotel_invoice_rooms: [
                    {
                        id: 14,
                        room_name: "Single Room",
                        total_room: 2,
                        total_price: "2.00",
                        currency_id: 1,
                        exchange_rate: "122.00",
                        commission_type: "percent",
                        commission_value: "20.00",
                        hotel_given_price: null,
                    },
                    {
                        id: 15,
                        room_name: "Double Room",
                        total_room: 2,
                        total_price: "300.00",
                        currency_id: 1,
                        exchange_rate: "122.00",
                        commission_type: "percent",
                        commission_value: "20.00",
                        hotel_given_price: null,
                    },
                ],
            },
        ],

    },
};
